# 003 List & numpy arrays

In [22]:
import numpy as np
#lists
#numpy arrays 


In [23]:
alist = [0,1,2,3,4,5]
type(alist)

list

In [24]:
listlist = [ 3, ['3', '4', '5'], 5.5, [4 , 5, 6 ] ]
listlist

[3, ['3', '4', '5'], 5.5, [4, 5, 6]]

In [25]:
listlist = [ 
    3,                  #a number
    ['3', '4', '5'],    #a list of strings
    5.5,                #float number
    [4 , 5, 6 ]         #a list of integer
    ]
listlist

[3, ['3', '4', '5'], 5.5, [4, 5, 6]]

In [26]:
blist = [0,1,2,3,4,5]
slist = ['0','1','2','3','4','5']

blist + slist

[0, 1, 2, 3, 4, 5, '0', '1', '2', '3', '4', '5']

In [27]:
slist + slist

['0', '1', '2', '3', '4', '5', '0', '1', '2', '3', '4', '5']

In [28]:
slist * 3

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5']

In [29]:
blist * 3

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [30]:
blist_np = np.array(blist)

print(type(blist))
print(type(blist_np))

print(blist)
print(blist_np)

<class 'list'>
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [31]:
blist_np * 3

array([ 0,  3,  6,  9, 12, 15])

In [32]:
print(blist_np *3)

[ 0  3  6  9 12 15]


In [33]:
#blist + 3 # data type list and data type int. will produce error
blist + blist # both data type list, can proceed
blist + [3]

[0, 1, 2, 3, 4, 5, 3]

In [34]:
s = 'shafiq'
for i , letter in enumerate(s):
    print(i , letter)

0 s
1 h
2 a
3 f
4 i
5 q


In [37]:
t = str(type(blist))[8:]

t[8:]
apost = t.find("'")
apost

4

# Execise

In [36]:
for idx, item in enumerate(listlist):
    print(f'List element {idx} is {item} and is of type {type(item)}.')

List element 0 is 3 and is of type <class 'int'>.
List element 1 is ['3', '4', '5'] and is of type <class 'list'>.
List element 2 is 5.5 and is of type <class 'float'>.
List element 3 is [4, 5, 6] and is of type <class 'list'>.


In [38]:
for idx, item in enumerate(listlist):
    t = str(type(item))[8:]
    apost = t.find("'")
    print(f'List element {idx} is {item} and is of type {t[:apost]}.')

List element 0 is 3 and is of type int.
List element 1 is ['3', '4', '5'] and is of type list.
List element 2 is 5.5 and is of type float.
List element 3 is [4, 5, 6] and is of type list.
