# 005 Creating and accessing matrices with numpy

In [3]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [5]:
A = np.array([[1,2], [3,4]])
print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [8]:
mat = np.zeros([4,6])  # 4 rows and 6 column

mat[0,1] = 2  # 0th row, 2nd column is 2
mat[2,4] = 7  # 3rd row, 5th column is 7

mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [11]:
numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi, coli] = (-1)**(rowi + coli)

mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [12]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [13]:
x,y = sym.symbols('x y')
Fxy = (4+x)*(2-y)

xyset = range(0,3)

outmat = np.zeros([len(xyset), len(xyset)])

for i in xyset:
    for j in xyset:
        outmat[i,j] = Fxy.subs({x:i, y:j})

display(Math(sym.latex(sym.sympify(outmat))))

<IPython.core.display.Math object>