# 003 Differences (Discrete Derivative)

In [1]:
import numpy as np

In [3]:
x = [1,3,4,-4]
np.diff(x)
print(np.diff(x))

[ 2  1 -8]


In [4]:
v = np.arange(0,11)
print(v)
print(np.diff(v))
print(np.diff(v,2))
print(np.diff(np.diff(v)))

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


# Exercise