# 007 Matrix Multiplication

In [33]:
import numpy as np

In [34]:
A = np.random.randn(14,10)
B = np.random.randn(14,10)
C = np.random.randn(10,14)

# 10 x 14 14 x 10
print(np.shape(C@B))
print(np.shape(B@C))

(10, 10)
(14, 14)


# Exercise

In [35]:
def matrixMultiplication(x,y):

    # get matrix sizes
    szX = np.shape(x)
    szY = np.shape(y)

    # check sizes and give error if multiplication is not valid
    if szX[1]!=szY[0]:
        raise ValueError('"Inner" dimension don\'t match ')
    
    # initialize
    z = np.zeros((szX[0],szY[1]))

    # compute!
    for i in range(szX[0]):
        for j in range(szY[1]):
            z[i,j] = np.dot( x[i,:], y[:,j])
    
    return z

In [36]:
x = np.random.randn(4,6)
y = np.random.randn(6,4)

z1 = matrixMultiplication(x,y)
z2 = x@y

print(z1)
print(z1-z2)

[[ 1.58272929 -2.29670491 -0.91552113  0.11058128]
 [ 0.00618497 -3.83976143 -0.02832866 -1.46055124]
 [-1.49589077  2.96168702 -1.16464035 -0.07445615]
 [-1.03462099 -3.31211779  1.20064461 -1.0224788 ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
