# 009 Various Special Matrices

In [5]:
import numpy as np 
import matplotlib.pyplot as plt

In [6]:
# identity matrix

I = np.eye(7)
print(I)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [7]:
# zero matrix
z = np.zeros((4,14))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
# diagonal matrix
D = np.diag([1,4,6,3,0])
print(D)
d = np.diagonal(np.random.randn(6,6))
print(d)

[[1 0 0 0 0]
 [0 4 0 0 0]
 [0 0 6 0 0]
 [0 0 0 3 0]
 [0 0 0 0 0]]
[-2.37180865 -0.72136755  0.57613295  1.06027621  0.35242956  1.73398543]
